name: Hello World Cron

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: |
          echo "Hello World"
          echo "Running on branch: $GITHUB_REF_NAME"
